### ISSUE TITLE
Can you add a license to your Nix repository?

### ISSUE THREAD

**Issue by collinarnett** [jpetrucciani/jpetrucciani#1]
Sorry to get in contact with you this way but you've disabled issues on your nix repository and I am unable to message you on linkedin or twitter. 

I would like to use some of the code in nix but I don't know under what circumstances I am allowed to use your code.

**Comment by jpetrucciani** [comment]
Oh apologies - I'm not sure why I had that disabled, but I've re-enabled it on that repo.

I've also added the MIT license to my nix repo now!
